In [14]:
import numpy as np 
import pandas as pd 

In [15]:
data=pd.read_csv("/content/SalesKaggle3.csv")
data.head(5)

Order   File_Type  SKU_number  SoldFlag  SoldCount MarketingType  \
0      2  Historical     1737127       0.0        0.0             D   
1      3  Historical     3255963       0.0        0.0             D   
2      4  Historical      612701       0.0        0.0             D   
3      6  Historical      115883       1.0        1.0             D   
4      7  Historical      863939       1.0        1.0             D   

   ReleaseNumber  New_Release_Flag  StrengthFactor  PriceReg  ReleaseYear  \
0             15                 1        682743.0     44.99         2015   
1              7                 1       1016014.0     24.81         2005   
2              0                 0        340464.0     46.00         2013   
3              4                 1        334011.0    100.00         2006   
4              2                 1       1287938.0    121.95         2010   

   ItemCount  LowUserPrice  LowNetPrice  
0          8         28.97        31.84  
1         39          0.00        15.54  
2         34         30.19        27.97  
3         20        133.93        83.15  
4         28          4.00        23.99

In [16]:
data.isnull()

Order  File_Type  SKU_number  SoldFlag  SoldCount  MarketingType  \
0       False      False       False     False      False          False   
1       False      False       False     False      False          False   
2       False      False       False     False      False          False   
3       False      False       False     False      False          False   
4       False      False       False     False      False          False   
...       ...        ...         ...       ...        ...            ...   
198912  False      False       False      True       True          False   
198913  False      False       False      True       True          False   
198914  False      False       False      True       True          False   
198915  False      False       False      True       True          False   
198916  False      False       False      True       True          False   

        ReleaseNumber  New_Release_Flag  StrengthFactor  PriceReg  \
0               False             False           False     False   
1               False             False           False     False   
2               False             False           False     False   
3               False             False           False     False   
4               False             False           False     False   
...               ...               ...             ...       ...   
198912          False             False           False     False   
198913          False             False           False     False   
198914          False             False           False     False   
198915          False             False           False     False   
198916          False             False           False     False   

        ReleaseYear  ItemCount  LowUserPrice  LowNetPrice  
0             False      False         False        False  
1             False      False         False        False  
2             False      False         False        False  
3             False      False         False        False  
4             False      False         False        False  
...             ...        ...           ...          ...  
198912        False      False         False        False  
198913        False      False         False        False  
198914        False      False         False        False  
198915        False      False         False        False  
198916        False      False         False        False  

[198917 rows x 14 columns]

In [17]:
data['New_Release_Flag'].unique()

array([1, 0])

In [18]:
data['File_Type'].unique()

array(['Historical', 'Active'], dtype=object)

In [19]:
data.drop(['Order','MarketingType','ReleaseYear','SoldCount','SoldFlag','ReleaseNumber','File_Type'],axis=1,inplace=True)

In [20]:
data.replace(to_replace='Historical',value=0,inplace=True)
data.replace(to_replace='Active',value=1,inplace=True)

In [21]:
data.head(192046)

SKU_number  New_Release_Flag  StrengthFactor  PriceReg  ItemCount  \
0          1737127                 1    6.827430e+05     44.99          8   
1          3255963                 1    1.016014e+06     24.81         39   
2           612701                 0    3.404640e+05     46.00         34   
3           115883                 1    3.340110e+05    100.00         20   
4           863939                 1    1.287938e+06    121.95         28   
...            ...               ...             ...       ...        ...   
192041      533626                 1    2.418945e+05    172.95         68   
192042      133068                 1    5.988037e+05     84.00         34   
192043      701120                 0    4.302446e+05    110.00         27   
192044      244000                 1    3.270937e+04    148.95         91   
192045      599612                 0    1.642324e+03     16.00        515   

        LowUserPrice  LowNetPrice  
0              28.97        31.84  
1               0.00        15.54  
2              30.19        27.97  
3             133.93        83.15  
4               4.00        23.99  
...              ...          ...  
192041          4.00        21.02  
192042          4.00        18.99  
192043          7.64        32.54  
192044         44.94        62.99  
192045          4.00         7.98  

[192046 rows x 7 columns]

In [22]:
dep_var=data['New_Release_Flag']
indep_var = data.drop(['New_Release_Flag'],axis=1)

In [23]:
indep_var

SKU_number  StrengthFactor  PriceReg  ItemCount  LowUserPrice  \
0          1737127    6.827430e+05     44.99          8         28.97   
1          3255963    1.016014e+06     24.81         39          0.00   
2           612701    3.404640e+05     46.00         34         30.19   
3           115883    3.340110e+05    100.00         20        133.93   
4           863939    1.287938e+06    121.95         28          4.00   
...            ...             ...       ...        ...           ...   
198912      109683    2.101869e+05     72.87         54          8.46   
198913      416462    4.555041e+05    247.00         65          8.40   
198914      658242    1.692746e+05     50.00         23         23.98   
198915     2538340    3.775266e+05     46.95         23         27.42   
198916      416662    1.183068e+05    120.00         44         10.97   

        LowNetPrice  
0             31.84  
1             15.54  
2             27.97  
3             83.15  
4             23.99  
...             ...  
198912        60.59  
198913        74.85  
198914        32.62  
198915        37.89  
198916        60.67  

[198917 rows x 6 columns]

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(indep_var)
print(x)

[[4.31403193e-01 3.92728452e-02 3.55049292e-03 3.14712825e-03
  2.04876731e-03 1.66363704e-03]
 [8.19774127e-01 5.84434859e-02 1.95794019e-03 1.53422502e-02
  0.00000000e+00 8.11963557e-04]
 [1.43884083e-01 1.95840403e-02 3.63019947e-03 1.33752950e-02
  2.13504608e-03 1.46142990e-03]
 ...
 [1.55529053e-01 9.73676567e-03 3.94586899e-03 9.04799371e-03
  1.69587298e-03 1.70439197e-03]
 [6.36275768e-01 2.17159807e-02 3.70517098e-03 9.04799371e-03
  1.93915083e-03 1.97974898e-03]
 [9.37563207e-02 6.80496467e-03 9.47008558e-03 1.73092054e-02
  7.75801774e-04 3.17000187e-03]]


In [25]:
indep_var= pd.DataFrame(x,columns=indep_var.columns)
indep_var.head(5)

SKU_number  StrengthFactor  PriceReg  ItemCount  LowUserPrice  LowNetPrice
0    0.431403        0.039273  0.003550   0.003147      0.002049     0.001664
1    0.819774        0.058443  0.001958   0.015342      0.000000     0.000812
2    0.143884        0.019584  0.003630   0.013375      0.002135     0.001461
3    0.016846        0.019213  0.007892   0.007868      0.009472     0.004345
4    0.208126        0.074085  0.009624   0.011015      0.000283     0.001253

In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(indep_var)
principal_components = pca.transform(indep_var)
pca.explained_variance_ratio_

array([0.86612019, 0.12851951, 0.00337588, 0.00089475])

In [27]:
print(abs( pca.components_ ))

[[0.99643616 0.08233808 0.00438764 0.01770002 0.00126592 0.00112534]
 [0.08289543 0.99592236 0.00516479 0.03494454 0.00202393 0.00388665]
 [0.01489194 0.03625958 0.0273191  0.99830783 0.00216718 0.03307434]
 [0.00326128 0.00635389 0.7393859  0.00203575 0.14670425 0.65706256]]


In [28]:
principaldata=data.drop(['New_Release_Flag','LowUserPrice','LowNetPrice'], axis=1)
principaldata.head(5)

SKU_number  StrengthFactor  PriceReg  ItemCount
0     1737127        682743.0     44.99          8
1     3255963       1016014.0     24.81         39
2      612701        340464.0     46.00         34
3      115883        334011.0    100.00         20
4      863939       1287938.0    121.95         28

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(principaldata,dep_var,test_size=0.2,random_state=43)

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [34]:
model1 = LogisticRegression()
model2 = RandomForestClassifier()
model3 = KNeighborsClassifier()
model4 = GaussianNB()

In [32]:
model1.fit(x_train,y_train)
pred1=model1.predict(x_test)
print(accuracy_score(y_test,pred1))

0.5974512366780615


In [33]:
model2.fit(x_train,y_train)
pred2=model2.predict(x_test)
print(accuracy_score(y_test,pred2))

KeyboardInterrupt: ignored

In [35]:
model3.fit(x_train,y_train)
pred3=model3.predict(x_test)
print(accuracy_score(y_test,pred3))

0.686582545747034


In [36]:
model4.fit(x_train,y_train)
pred4=model4.predict(x_test)
print(accuracy_score(y_test,pred4))

0.6878896038608486


In [ ]:
# import pickle
# pickle.dump(model2,open('sales_analysis.pkl','wb'))

In [37]:
import pickle
pickle.dump(model4,open('sales_analysis.pkl','wb'))

In [40]:
confusion_matrix(y_test,pred1)

array([[ 7372,  6722],
       [ 9293, 16397]])

In [39]:
confusion_matrix(y_test,pred2)

NameError: ignored

In [41]:
confusion_matrix(y_test,pred3)

array([[ 6703,  7391],
       [ 5078, 20612]])

In [42]:
confusion_matrix(y_test,pred4)

array([[ 4964,  9130],
       [ 3287, 22403]])

In [43]:
x_test.head(5)

SKU_number  StrengthFactor  PriceReg  ItemCount
104858      228988    279783.62250     16.00         22
176525      227086      2377.69125     16.95         46
74019       541735    553961.00000     45.00         24
60645       290206     79262.00000     73.98         40
5375        121195      9912.00000    177.80         79

In [44]:
x_test.loc[x_test['SKU_number'] == 599612]

SKU_number  StrengthFactor  PriceReg  ItemCount
192045      599612      1642.32375      16.0        515

In [45]:
model4.predict(x_test.loc[x_test['SKU_number'] == 599612])

array([1])